version: "3"

services:
  app:
    image: golang
    volumes:
      - gopath:/go
      - go-build:/root/.cache/go-build
      - .:/app:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DC_ASSIGNMENT_PATH:-./assignments}:/assignments:ro
    working_dir: /app
    command: go run -v .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - UA_DATABASE=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable
      - UA_MIGRATE_UP=true
      - UA_ASSIGNMENT_PATH=/assignments

  db:
    image: postgres

volumes:
  gopath:
  go-build:
