// This file is automatically generated by qtc from "assignments.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/assignments.qtpl:1
package templates

//line templates/assignments.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/assignments.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/assignments.qtpl:1
func StreamAssignments(qw422016 *qt422016.Writer, id string) {
	//line templates/assignments.qtpl:1
	qw422016.N().S(`
<!doctype html>
<html>

<head>
</head>

<body>
<p>
<a href="/docker/`)
	//line templates/assignments.qtpl:10
	qw422016.E().S(id)
	//line templates/assignments.qtpl:10
	qw422016.N().S(`">`)
	//line templates/assignments.qtpl:10
	qw422016.E().S(id)
	//line templates/assignments.qtpl:10
	qw422016.N().S(`</a>
</p>
</body>

</html>
`)
//line templates/assignments.qtpl:15
}

//line templates/assignments.qtpl:15
func WriteAssignments(qq422016 qtio422016.Writer, id string) {
	//line templates/assignments.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/assignments.qtpl:15
	StreamAssignments(qw422016, id)
	//line templates/assignments.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line templates/assignments.qtpl:15
}

//line templates/assignments.qtpl:15
func Assignments(id string) string {
	//line templates/assignments.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/assignments.qtpl:15
	WriteAssignments(qb422016, id)
	//line templates/assignments.qtpl:15
	qs422016 := string(qb422016.B)
	//line templates/assignments.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/assignments.qtpl:15
	return qs422016
//line templates/assignments.qtpl:15
}
