// This file is automatically generated by qtc from "docker.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/docker.qtpl:1
package templates

//line templates/docker.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/docker.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/docker.qtpl:1
func StreamDocker(qw422016 *qt422016.Writer, id string) {
	//line templates/docker.qtpl:1
	qw422016.N().S(`
<!doctype html>
<html>

<head>
<link rel="stylesheet" href="/static/bower_components/xterm.js/dist/xterm.css" />
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,700,300">
<script src="/static/bower_components/xterm.js/dist/xterm.js"></script>
<script src="/static/bower_components/xterm.js/dist/addons/terminado/terminado.js"></script>

<style type="text/css">
#terminal > .terminal {
    font-family: "Roboto Mono", monospace !important;
}
</style>
</head>

<body>

<div id="terminal"></div>

<script>
term = new Terminal({cursorBlink: true});
var sock = new WebSocket("ws://" + document.location.host + "/docker/`)
	//line templates/docker.qtpl:24
	qw422016.E().S(id)
	//line templates/docker.qtpl:24
	qw422016.N().S(`/ws");
term.terminadoAttach(sock, true, false);
term.open(document.getElementById('#terminal'));
</script>

</body>

</html>
`)
//line templates/docker.qtpl:32
}

//line templates/docker.qtpl:32
func WriteDocker(qq422016 qtio422016.Writer, id string) {
	//line templates/docker.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/docker.qtpl:32
	StreamDocker(qw422016, id)
	//line templates/docker.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line templates/docker.qtpl:32
}

//line templates/docker.qtpl:32
func Docker(id string) string {
	//line templates/docker.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/docker.qtpl:32
	WriteDocker(qb422016, id)
	//line templates/docker.qtpl:32
	qs422016 := string(qb422016.B)
	//line templates/docker.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/docker.qtpl:32
	return qs422016
//line templates/docker.qtpl:32
}
